name: Pipeline Enforcer Action
description: This action protects your GitHub workflows by generating a profile of your workflow job activity and enforcing policies on it
inputs:
  access-token:
    description: 'SCM access token'
    default: '${{ github.token }}'
    required: true
  aqua-key:
    description: 'Aqua key'
    required: true
  aqua-secret:
    description: 'Aqua secret'
    required: true
  repo-path:
    description: 'Path to the repository'
    required: false
  quiet:
    description: 'Print only errors'
    default: 'false'
    required: false
  verbose:
    description: 'Print debug logs and above'
    default: 'false'
    required: false
  log-file:
    description: 'Path to the log file'
    required: false
  matrix-context:
    description: 'Matrix context'
    required: false
    default: '${{ toJSON(matrix) }}'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
