name: Tracee Commercial Action
description: |
  This action is used to protect your GitHub workflows by generating a profile of your workflow job using Aqua Security's Tracee.
  The profile provides visibility of your workflow jobs and allows you to enforce policies from Aqua platform.
  To use this action, you need to have an Aqua account and generate a key and a secret from Aqua platform.
inputs:
  access-token:
    description: 'SCM access token'
    default: '${{ github.token }}'
    required: true
  aqua-key:
    description: 'Aqua key'
    required: true
  aqua-secret:
    description: 'Aqua secret'
    required: true
  repo-path:
    description: 'Path to the repository'
    required: false
  quiet:
    description: 'Print only errors'
    default: 'false'
    required: false
  verbose:
    description: 'Print debug logs and above'
    default: 'false'
    required: false
  log-file:
    description: 'Path to the log file'
    required: false
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
